package KlasyGlowne;



import Interfejsy.StworzNowaGreListener;
import Interfejsy.StworzNowaGrePodmiot;
import java.awt.event.MouseListener;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nogaz
 */
public class NowaGraDialog extends javax.swing.JDialog implements StworzNowaGrePodmiot{

    private StworzNowaGreListener obserwator;
    
    /**
     * Creates new form NowaGraDialog
     */
    public NowaGraDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        trybGryLabel = new javax.swing.JLabel();
        poziomTrudnosciLabel = new javax.swing.JLabel();
        PvPradioButton = new javax.swing.JRadioButton();
        PvPgracz1TextField = new javax.swing.JTextField();
        PvPgracz2TextField = new javax.swing.JTextField();
        PvCradioButton = new javax.swing.JRadioButton();
        PvCgracz1TextField = new javax.swing.JTextField();
        CvCradioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPoziomowTrudnosciCPU1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPoziomowTrudnosciCPU2 = new javax.swing.JList();
        grajButton = new javax.swing.JButton();
        anulujButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ustawienia nowej gry");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 300));

        trybGryLabel.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        trybGryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trybGryLabel.setText("Tryb gry:");
        trybGryLabel.setMaximumSize(new java.awt.Dimension(170, 60));
        trybGryLabel.setMinimumSize(new java.awt.Dimension(170, 60));
        trybGryLabel.setPreferredSize(new java.awt.Dimension(170, 60));

        poziomTrudnosciLabel.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        poziomTrudnosciLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        poziomTrudnosciLabel.setText("Poziom trudności:");
        poziomTrudnosciLabel.setMaximumSize(new java.awt.Dimension(170, 60));
        poziomTrudnosciLabel.setMinimumSize(new java.awt.Dimension(170, 60));
        poziomTrudnosciLabel.setPreferredSize(new java.awt.Dimension(170, 60));

        buttonGroup1.add(PvPradioButton);
        PvPradioButton.setMnemonic('1');
        PvPradioButton.setSelected(true);
        PvPradioButton.setText("Gracz1 vs Gracz2");
        PvPradioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PvPradioButtonActionPerformed(evt);
            }
        });

        PvPgracz1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PvPgracz1TextField.setText("Gracz1");
        PvPgracz1TextField.setMaximumSize(new java.awt.Dimension(80, 30));
        PvPgracz1TextField.setMinimumSize(new java.awt.Dimension(80, 30));
        PvPgracz1TextField.setPreferredSize(new java.awt.Dimension(80, 30));
        PvPgracz1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PvPgracz1TextFieldActionPerformed(evt);
            }
        });

        PvPgracz2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PvPgracz2TextField.setText("Gracz2");
        PvPgracz2TextField.setMaximumSize(new java.awt.Dimension(80, 30));
        PvPgracz2TextField.setMinimumSize(new java.awt.Dimension(80, 30));
        PvPgracz2TextField.setPreferredSize(new java.awt.Dimension(80, 30));

        buttonGroup1.add(PvCradioButton);
        PvCradioButton.setMnemonic('2');
        PvCradioButton.setText("Gracz1 vs CPU");
        PvCradioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PvCradioButtonActionPerformed(evt);
            }
        });

        PvCgracz1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PvCgracz1TextField.setText("Gracz1");
        PvCgracz1TextField.setMaximumSize(new java.awt.Dimension(80, 30));
        PvCgracz1TextField.setMinimumSize(new java.awt.Dimension(80, 30));
        PvCgracz1TextField.setPreferredSize(new java.awt.Dimension(80, 30));

        buttonGroup1.add(CvCradioButton);
        CvCradioButton.setMnemonic('3');
        CvCradioButton.setText("CPU vs CPU");
        CvCradioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CvCradioButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CPU1");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CPU2");
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 30));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(80, 100));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(80, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(80, 100));

        listaPoziomowTrudnosciCPU1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "poziom1", "poziom2", "poziom3", "poziom4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaPoziomowTrudnosciCPU1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPoziomowTrudnosciCPU1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaPoziomowTrudnosciCPU1.setEnabled(false);
        listaPoziomowTrudnosciCPU1.setMaximumSize(new java.awt.Dimension(80, 100));
        listaPoziomowTrudnosciCPU1.setMinimumSize(new java.awt.Dimension(80, 100));
        listaPoziomowTrudnosciCPU1.setPreferredSize(new java.awt.Dimension(80, 100));
        jScrollPane1.setViewportView(listaPoziomowTrudnosciCPU1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(80, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(80, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(80, 100));

        listaPoziomowTrudnosciCPU2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "poziom1", "poziom2", "poziom3", "poziom4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaPoziomowTrudnosciCPU2.setEnabled(false);
        listaPoziomowTrudnosciCPU2.setMaximumSize(new java.awt.Dimension(80, 100));
        listaPoziomowTrudnosciCPU2.setMinimumSize(new java.awt.Dimension(80, 100));
        listaPoziomowTrudnosciCPU2.setPreferredSize(new java.awt.Dimension(80, 100));
        jScrollPane2.setViewportView(listaPoziomowTrudnosciCPU2);

        grajButton.setText("Graj");
        grajButton.setMaximumSize(new java.awt.Dimension(170, 60));
        grajButton.setMinimumSize(new java.awt.Dimension(170, 60));
        grajButton.setPreferredSize(new java.awt.Dimension(170, 60));
        grajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grajButtonActionPerformed(evt);
            }
        });

        anulujButton.setText("Anuluj");
        anulujButton.setMaximumSize(new java.awt.Dimension(170, 60));
        anulujButton.setMinimumSize(new java.awt.Dimension(170, 60));
        anulujButton.setPreferredSize(new java.awt.Dimension(170, 60));
        anulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(grajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trybGryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CvCradioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PvCradioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PvPradioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(PvPgracz1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PvPgracz2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PvCgracz1TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poziomTrudnosciLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(anulujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poziomTrudnosciLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trybGryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PvPradioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PvPgracz1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PvCradioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PvCgracz1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CvCradioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(PvPgracz2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anulujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PvPgracz1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PvPgracz1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PvPgracz1TextFieldActionPerformed

    private void PvPradioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PvPradioButtonActionPerformed
        // TODO add your handling code here:
        /*...........
        GRACZ ZAZNACZYL OPCJE PvP:
            -   AKTYWUJ POLA DO WPISYWANIA NAZW GRACZY DLA TRYBU PvP
            -   DEZAKTYWUJ POLE DO WPISYWANIA NAZWY GRACZA DLA TRYBU PvC
            -   DEZAKTYWUJ OBIE LISTY POZIOMOW TRUDNOSCI CPU
        ...........*/
        this.PvPgracz1TextField.setEnabled(true);
        this.PvPgracz2TextField.setEnabled(true);
        
        this.PvCgracz1TextField.setEnabled(false);
        
        this.listaPoziomowTrudnosciCPU1.setEnabled(false);
        this.listaPoziomowTrudnosciCPU2.setEnabled(false);
    }//GEN-LAST:event_PvPradioButtonActionPerformed

    private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButtonActionPerformed
        /*........
        ZAMKNIJ OKNO DIALOGOWE
        ........*/
        this.setVisible(false);
    }//GEN-LAST:event_anulujButtonActionPerformed

    private void PvCradioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PvCradioButtonActionPerformed
        /*...........
        GRACZ ZAZNACZYL OPCJE PvC:
            -   AKTYWUJ POLA DO WPISYWANIA NAZWy GRACZa DLA TRYBU PvC
            -   DEZAKTYWUJ POLA DO WPISYWANIA NAZWY GRACZY DLA TRYBU PvP
            -   DEZAKTYWUJ LISTE POZIOMOW TRUDNOSCI CPU2
        ...........*/
        this.PvCgracz1TextField.setEnabled(true);
        
        this.PvPgracz1TextField.setEnabled(false);
        this.PvPgracz2TextField.setEnabled(false);
        
        this.listaPoziomowTrudnosciCPU1.setEnabled(true);
        this.listaPoziomowTrudnosciCPU2.setEnabled(false);
    }//GEN-LAST:event_PvCradioButtonActionPerformed

    private void CvCradioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CvCradioButtonActionPerformed
        /*...........
        GRACZ ZAZNACZYL OPCJE PvC:
            -   DEZAKTYWUJ POLA DO WPISYWANIA NAZWY GRACZA DLA TRYBU PvC
            -   DEZAKTYWUJ POLA DO WPISYWANIA NAZWY GRACZY DLA TRYBU PvP
            -   AKTYWUJ LISTY POZIOMOW TRUDNOSCI CPU1 i CPU2
        ...........*/
        this.PvCgracz1TextField.setEnabled(false);
        
        this.PvPgracz1TextField.setEnabled(false);
        this.PvPgracz2TextField.setEnabled(false);
        
        this.listaPoziomowTrudnosciCPU1.setEnabled(true);
        this.listaPoziomowTrudnosciCPU2.setEnabled(true);
    }//GEN-LAST:event_CvCradioButtonActionPerformed

    private void grajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grajButtonActionPerformed
        /*............
        GRACZ URUCHOMIL NOWA GRE
            - WYCZYSC PLANSZE
            - USTAW NAZWE GRACZA
            - UTWORZ ODPOWIEDNI OBIEKT GRY(pvp, pvc, cvc)
        .............*/
        int trybGry = this.buttonGroup1.getSelection().getMnemonic();
        String imieGracza1;
        String imieGracza2;
        int poziomTrudnosciCPU1;
        String poziomTrudnosciCPU1str;
        int poziomTrudnosciCPU2;
        String poziomTrudnosciCPU2str;
        
        if( trybGry == 49 ){
            if( (PvPgracz1TextField.getText() != null) && (PvPgracz2TextField.getText() != null) ){
                imieGracza1 = PvPgracz1TextField.getText();
                imieGracza2 = PvPgracz2TextField.getText();
                
                System.out.println("Parametry tworzonej gry PvP:");
                System.out.println("Gracz1: " + imieGracza1);
                System.out.println("Gracz2: " + imieGracza2);
                //uruchom gre w trybie PVP
                powiadomObserwatorow(trybGry, imieGracza1, imieGracza2);
                this.setVisible(false);
            }
        }else if( trybGry == 50 ){
            if( (listaPoziomowTrudnosciCPU1.getSelectedValue() != null) && (PvCgracz1TextField.getText() != null) ){
                poziomTrudnosciCPU1str = listaPoziomowTrudnosciCPU1.getSelectedValue().toString();
                System.out.println("Wybrałem tryb gry Player vs Cpu");
                System.out.println("Poziom trudnosci CPU1: " + poziomTrudnosciCPU1str );
                imieGracza1 = PvCgracz1TextField.getText();
                
                System.out.println("Parametry tworzonej gry PvC:");
                System.out.println("Gracz1: " + imieGracza1);
                System.out.println("Gracz2(CPU): " + poziomTrudnosciCPU1str);
                System.out.println();
                //uruchom gre w trybie PVC    
                powiadomObserwatorow(trybGry, imieGracza1, poziomTrudnosciCPU1str);
                this.setVisible(false);
            }
            
        }else if(trybGry == 51 ){
            //uruchom gre w trybie CvC
            if( (listaPoziomowTrudnosciCPU1.getSelectedValue() != null) && (listaPoziomowTrudnosciCPU2.getSelectedValue() != null)){
                poziomTrudnosciCPU1str = listaPoziomowTrudnosciCPU1.getSelectedValue().toString();
                poziomTrudnosciCPU2str = listaPoziomowTrudnosciCPU2.getSelectedValue().toString();
                //poziomTrudnosciCPU1 = listaPoziomowTrudnosciCpu1.getSelectedValue();
                
                System.out.println("Parametry tworzonej gry CvC:");
                System.out.println("Gracz1(CPU): " + poziomTrudnosciCPU1str);
                System.out.println("Gracz2(CPU): " + poziomTrudnosciCPU2str);
                System.out.println();
                //uruchom gre w trybie CvC
                powiadomObserwatorow(trybGry, poziomTrudnosciCPU1str, poziomTrudnosciCPU2str);
                this.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_grajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NowaGraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NowaGraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NowaGraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NowaGraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NowaGraDialog dialog = new NowaGraDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CvCradioButton;
    private javax.swing.JTextField PvCgracz1TextField;
    private javax.swing.JRadioButton PvCradioButton;
    private javax.swing.JTextField PvPgracz1TextField;
    private javax.swing.JTextField PvPgracz2TextField;
    private javax.swing.JRadioButton PvPradioButton;
    private javax.swing.JButton anulujButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton grajButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaPoziomowTrudnosciCPU1;
    private javax.swing.JList listaPoziomowTrudnosciCPU2;
    private javax.swing.JLabel poziomTrudnosciLabel;
    private javax.swing.JLabel trybGryLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void zarejestrujObserwatora(StworzNowaGreListener o) {
        obserwator = o;
    }

    @Override
    public void usunObserwatora(StworzNowaGreListener o) {
        obserwator = null;
    }

    @Override
    public void powiadomObserwatorow(int trybgry, String gracz1, String gracz2) {
        /*for( int i = 0 ; i < obserwatorzy.size() ; ++i ){
            StworzGreObserwator obs = (StworzGreObserwator)obserwatorzy.get(i);
            obs.stworzNowaGre(trybgry, gracz1, gracz2);
        }*/
        obserwator.stworzNowaGre(trybgry, gracz1, gracz2);
    }
}
